#!/bin/bash
# vim: set ts=4 sw=4 sts=4 et :

### prepare-chroot-builder : create a builder chroot instance of Gentoo

set -e
if [ "${VERBOSE:-0}" -ge 2 ] || [ "${DEBUG:-0}" -eq 1 ]; then
    set -x
fi

INSTALLDIR="$1"
DISTRO="$2"

[ -z "$CACHEDIR" ] && CACHEDIR="/tmp"

SCRIPTSDIR=${GENTOO_PLUGIN_DIR}scripts
export INSTALLDIR SCRIPTSDIR

# shellcheck source=scripts/distribution.sh
. ${SCRIPTSDIR}/distribution.sh

if ! [ -d "${INSTALLDIR}/home/user" ]; then
    mkdir -p "$INSTALLDIR"

    "${GENTOO_PLUGIN_DIR}/prepare-chroot-base" "$INSTALLDIR" "$DISTRO"

    [ -n "$SUDO_UID" ] && USER_OPTS="-u ${SUDO_UID}"
    [ -n "$USER_UID" ] && USER_OPTS="-u ${USER_UID}"
    if [ -n "$USER_GID" ]; then
        chroot "$INSTALLDIR" /usr/sbin/groupadd -g "$USER_GID" user
    elif [ -n "$SUDO_GID" ]; then
        chroot "$INSTALLDIR" /usr/sbin/groupadd -g "$SUDO_GID" user
    else
        chroot "$INSTALLDIR" /usr/sbin/groupadd user
    fi
    chroot "$INSTALLDIR" /bin/bash -c \
        "useradd -g user -G wheel $USER_OPTS -m user; su -c 'mkdir qubes-src' - user"

    cat > "${INSTALLDIR}/etc/sudoers.d/qubes-builder-user" <<EOF
%wheel ALL=(ALL) NOPASSWD: ALL
EOF

    if ! [ -r "${INSTALLDIR}"/tmp/qubes-packages-mirror-repo/.mnt ]; then
        mkdir -p "${INSTALLDIR}"/tmp/qubes-packages-mirror-repo
        mount --bind "${BUILDER_REPO_DIR}" "${INSTALLDIR}/tmp/qubes-packages-mirror-repo"
    fi
fi

prepareChroot "${INSTALLDIR}"
mountCache "${CACHEDIR}" "${INSTALLDIR}"

# builder-local overlay
setupBuilderOverlay "${INSTALLDIR}"

# Standard Gentoo flags
setupBaseFlags "${INSTALLDIR}" "${TEMPLATE_FLAVOR}"

# Qubes Gentoo flags
setupQubesFlags "${INSTALLDIR}" "${TEMPLATE_FLAVOR}"

if [ -z "$TEMPLATE_FLAVOR" ] || [ "$TEMPLATE_FLAVOR" == "xfce" ] || [ "$TEMPLATE_FLAVOR" == "gnome" ]; then
    # Select desktop/gnome/systemd profile
    chrootCmd "${INSTALLDIR}" "eselect profile set default/linux/amd64/17.1/desktop/gnome/systemd"
fi

updateChroot "${INSTALLDIR}"